name: Pre PR Checks
on: push
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Src
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install NPM Deps
        run: |
          cd angular-app/
          npm i
      - name: ESlint Check
        run: |
          cd angular-app/
          npm run lint
      - name: Angular Unit Tests
        run: |
          cd angular-app/
          npm test -- --watch=false --browsers=ChromeHeadless
      - name: Angular Project Build
        run: |
          cd angular-app/
          npm run build
