name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Src
        uses: actions/checkout@v3
      - name: Update NodeJS to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install JS deps
        run: npm ci
      - name: Run Angular Tests
        run: |
          cd angular-app/
          ng test
